@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/CustomerEnablement/rePost.puml
!include AWSPuml/DeveloperTools/CodeCommit.puml
!include AWSPuml/DeveloperTools/CodeDeploy.puml
!include AWSPuml/MachineLearning/DeepLearningAMIs.puml
!include AWSPuml/MigrationTransfer/TransferFamily.puml

hide footbox
skinparam roundcorner 20
skinparam sequenceMessageAlign left
skinparam sequenceLifeLineBorderColor AWS_COLOR
skinparam participantBackgroundColor AWS_BG_COLOR
skinparam actorBackgroundColor AWS_BORDER_COLOR
skinparam MaxMessageSize 400
skinparam responseMessageBelowArrow true

title
 Sequence Diagram of the Contribution Workflow
end title

actor User as user

box Local Dev
    participant "$CodeCommitIMG()\nBranch" as branch
endbox

box GitHub
    participant "$rePostIMG()\n[[https://github.com/crgz/abbreviated_dates/pulls {Pull Requests} Pull Requests]]" as pr
endbox

box [[https://github.com/crgz/abbreviated_dates/actions {GitHub Actions} GitHub Actions]]
    participant "$DeepLearningAMIsIMG()\n[[https://github.com/crgz/abbreviated_dates/actions/workflows/01-test.yml {Tests Workflow} Tests]]" as test
    participant "$DeepLearningAMIsIMG()\n[[https://github.com/crgz/abbreviated_dates/actions/workflows/02-version.yml {Version Workflow} Version]]" as version
    participant "$DeepLearningAMIsIMG()\n[[https://github.com/crgz/abbreviated_dates/actions/workflows/03-release.yml {Release Workflow} Release]]" as release
    participant "$DeepLearningAMIsIMG()\n[[https://github.com/crgz/abbreviated_dates/actions/workflows/04-submit.yml {Submit Workflow} Submit]]" as submit
endbox

box GitHub
    participant "$TransferFamilyIMG()\n[[https://www.swi-prolog.org/pack/list {GitHub Releases} Releases]]" as store
endbox

box Distribution
    participant "$CodeDeployIMG()\n[[https://www.swi-prolog.org/pack/list {SWI-Prolog Packages} Packs]]" as deploy
endbox

user -> branch: Create/Update\nfeature branch
activate branch #00CCCC

branch -> pr++ #00CCCC: Create/Update\nPull Request

loop Until test pass
    pr -> test++ #009999: Test
    return Test Pass/Fail
end

user -> pr++ #00FF00: Label for Release
deactivate pr

user -> pr++ #Violet: Close
pr -> pr #00CCCC: Merge
pr -> version #00CCCC: Create Pull Request release
destroy pr
activate version #00CCCC
deactivate pr

alt label for release
    version -> version #00CCCC: Increment\nVersion
    version -> pr: Merge

    version -> release #00CCCC: Release
    destroy version

    activate release #00CCCC
    release -> store: store
    activate store  #DarkViolet
    release -> submit: Submit
    deactivate release

    activate submit #00CCCC
    submit -> deploy: Deploy
    deactivate submit

    activate deploy #DarkViolet
    deactivate deploy
else not label for release

end

user -> branch: Reset
branch -> pr: fetch
pr --> branch: Merge
branch -> branch: Delete
destroy branch

user -> deploy: Request Package
deploy -> store: Request Release
store -> deploy: Deliver Release
deploy -> user: Deliver Package

@enduml
