name: Run Unit Tests against source files included in a Pull Request targeting the main branch
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    if: "! startsWith(github.head_ref, 'release')"
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'prolog/**'
              - 'prolog/**/*'
        # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        name: Run Library Unit Tests
        run: make test
