name: Prepare Pull Request with bumped version targeting the release branch

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
jobs:
  bump_version:
    name: Prepare Pull Request with bumped version targeting the release branch
    if: github.event.pull_request.merged == true && ! startsWith(github.head_ref, 'release') && ${{ github.event.label.name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@v3
      - name: Increase version counter and update version dependent files
        run: make bump
      - name: Set the VERSION variable int he GitHub Environment
        run: echo "VERSION=$(awk -F=' ' '/current_version/{printf "v%s",$2}' .bumpversion.cfg)" >> $GITHUB_ENV
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          branch: release
          title: "Release: ${{ env.VERSION }} - ${{ github.event.pull_request.title }}"
          delete-branch: true
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
#      - name: Enable pull request automerge
#        uses: peter-evans/enable-pull-request-automerge@v2
#        with:
#          token: ${{ secrets.PAT }}
#          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
