name: Prepare a Pull Request with a new version targeting the release branch

on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
jobs:
  bump_version:
    name: Prepare a Pull Request with a new version targeting the release branch
    if: ${{ github.event.label.name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@v3
      - name: Increase version counter and update version dependent files
        run: make bump
      - name: Set the VERSION variable int he GitHub Environment
        run: echo "VERSION=$(awk -F=' ' '/current_version/{printf "v%s",$2}' .bumpversion.cfg)" >> $GITHUB_ENV
      - name: Set the VERSION variable int he GitHub Environment
        run: |
          git add .
          git commit -a -m "Release: ${{ env.VERSION }} - ${{ github.event.pull_request.title }}"
          git push

#      - name: Create a Pull Request to merge the version dependent files into the main branch from the release branch
#        id: cpr
#        uses: peter-evans/create-pull-request@v4
#        with:
#          token: ${{ secrets.PAT }}
#          branch: release
#          title: "Release: ${{ env.VERSION }} - ${{ github.event.pull_request.title }}"
#          delete-branch: true
#      - name: Check outputs
#        if: ${{ steps.cpr.outputs.pull-request-number }}
#        run: |
#          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
#          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
