name: Create a new Version with Pull Request targeting the release branch

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
jobs:
  bump_version:
    name: Create a new Version with Pull Request targeting the release branch
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release')) && ! startsWith(github.head_ref, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@v3
      - name: Install utilities
        run: sudo make utilities
      - name: Set the VERSION variable int the GitHub Environment
        run: echo "VERSION=$(awk -F=' ' '/current_version/{printf "v%s",$2}' .bumpversion.cfg)" >> $GITHUB_ENV
      - name: Increase version counter and update version dependent files
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          make committer \
          && (git push -d origin release || true) \
          && git checkout -b release \
          && bumpversion --allow-dirty --list patch \
          && git push origin release \
          && gh pr create -B main -H release --fill \
          && gh pr merge -m --auto --delete-branch
