name: Status
on:
  push:
    tags:
      - 'v*'
jobs:
  ship:
    name: Ship the new released package into the Library Supply Chain Infrastructure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Library Repository
      uses: actions/checkout@v3
    - name: Ship the new released package into the Library Supply Chain Infrastructure
      run: make install
