name: approve

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: approve
      run: |
        echo ${{ secrets.GITHUB_TOKEN }}
        curl --request PUT \
        --url https://api.github.com/repos/${{ github.repository }}/pulls/23/merge \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'

