name: Submit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Submit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make submit
