name: Create the release and ship the package to the Library Supply Chain Infrastructure
on:
  pull_request:
    types: [ closed ]
    branches:
      - main
jobs:
  submit:
    name: Submit package to Supply Chain
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: make release-from-github
    - name: Submit
      run: make install
