name: Create the release and ship the package to the Library Supply Chain Infrastructure
on:
  pull_request:
    types: [ closed ]
    branches:
      - release
jobs:
  submit:
    name: Submit package to Supply Chain
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: make release-from-github
    - name: Submit
      run: make install
