name: Submit
on:
  push:
    tags:
      - 'v*'
jobs:
  submit:
    name: Submit package to Supply Chain
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Submit
      run: make install
