name: Submit
on:
  release:
    types: [published]
jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Submit
      run: make install
